# Tensors
A tensor is an n-dimensional array.
## Scalar  (0-dimensional tensor)
0 dimesional tensor

In [1]:
import torch

x = torch.tensor(2)                      #  scalar with dtype int64 
y = torch.tensor(2.)                     #  scalar with dtype float32
z = torch.tensor(2, dtype=torch.double)  #  scalar with dtype float64
print("x     :", x)
print("item  :", x.item())                          #  item() returns the scalar value within the tensor
print("dtype :", x.dtype)                           # data type of the tensor values
print("dim   :", x.dim())                           # dimension of the tensor
print("numel :", x.numel())                         # number of elements in the tensor
 

x     : tensor(2)
item  : 2
dtype : torch.int64
dim   : 0
numel : 1


## 1-dimensional tensor

In [2]:
x = torch.tensor([1,2,3,4,5,6])   # Tensor from a list
y = torch.arange(1,7)             # Tensor using arange function
ones = torch.ones(7)
print("x   :", x)
print("y   :", y)
print("ones:", ones)
print("shape x: ", x.shape)
print("size  x: ", x.size())

x   : tensor([1, 2, 3, 4, 5, 6])
y   : tensor([1, 2, 3, 4, 5, 6])
ones: tensor([1., 1., 1., 1., 1., 1., 1.])
shape x:  torch.Size([6])
size  x:  torch.Size([6])


## 2-dimensional tensor, view(), eye(), diag(), zeros()

In [3]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])                       # 2D tensor from list of size 3,2
y = x.view(2,3)                                 # use view() to reshape the tensor
z = x.view(-1,3)                                # -1 states that infer the dimension from the remaining dimensions
t = x.reshape(2,3)                              # same as view but may copy underlying data
t[0,0] = -3
I = torch.eye(4)                                # unit matrix
diags = torch.diag(I)                           # diagonals of a matrix
zeros = torch.zeros(2,3, dtype=torch.int64)     # zero matrix default dtype is float32
print("x:", x)
print("y:", y) 
print("z:", z)
print("t:", t)
print(I)
print(diags)
print(ones)
print(zeros)

x: tensor([[-3,  2],
        [ 3,  4],
        [ 5,  6]])
y: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
z: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
t: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1.])
tensor([[0, 0, 0],
        [0, 0, 0]])


## n-dimensional tensor

In [4]:
x=torch.tensor([[[1,2,3],
                 [3,4,5]],
                [[6,7,9],
                 [9,10,11]]])                  # 3D tensor using list of shape 2,2,3
y = torch.rand(16,1,28,28)                     # uniform dist between 0,1 (16 1-channel(gray scale) 28x28 image)
z = torch.randn(1,1,2,2)                       # from normal distribution mu=0 std=1
ones = torch.ones(2,2,4)
print("x    :",x)
print("sie x:", x.size())
print(y)
print(t)

x    : tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[ 6,  7,  9],
         [ 9, 10, 11]]])
sie x: torch.Size([2, 2, 3])
tensor([[[[0.0097, 0.3974, 0.8461,  ..., 0.4768, 0.9119, 0.4705],
          [0.2760, 0.6648, 0.3551,  ..., 0.0503, 0.9283, 0.6480],
          [0.2382, 0.7161, 0.8290,  ..., 0.5961, 0.0448, 0.3058],
          ...,
          [0.8273, 0.0019, 0.2371,  ..., 0.5376, 0.2642, 0.6386],
          [0.7017, 0.7058, 0.1481,  ..., 0.7729, 0.8676, 0.0901],
          [0.2392, 0.7538, 0.5817,  ..., 0.2584, 0.7308, 0.7420]]],


        [[[0.9521, 0.5399, 0.5906,  ..., 0.2964, 0.5310, 0.2482],
          [0.0561, 0.0819, 0.9975,  ..., 0.0726, 0.4778, 0.2070],
          [0.2557, 0.2994, 0.0068,  ..., 0.0936, 0.7963, 0.4093],
          ...,
          [0.3516, 0.2803, 0.8027,  ..., 0.5946, 0.2107, 0.5075],
          [0.5876, 0.4730, 0.2368,  ..., 0.7977, 0.2009, 0.4347],
          [0.6668, 0.6688, 0.2132,  ..., 0.9232, 0.3933, 0.4522]]],


        [[[0.0671, 0.8058, 0.4026,  ..

## Aritmetic Operations

In [5]:
x = torch.tensor([6,8])
y = torch.tensor([3,4])
print(x+y)                     # sum
print(x.add(y))                # sum 2
print(x-y)                     # substract
print(x.sub(y))                # substract 2
print(x/y)                     # divide
print(x.div(y))                # divide 2print(torch.matmul(m2,m3))     # broadcasting
print(x*y)                     # element wise product
print(x@y)                     # dot product if both are 1-d tensor

print(x.add_(y))               # inline addition
print(x)                       # value of x has changed

m1 = torch.randn(2, 3)
m2 = torch.randn(3, 4)
m3 = torch.randn(1,3)
mult = torch.mm(m1,m2)         # no broadcast
print(mult)
mult2 = m1 @ m2                # matrix multiplication
print(mult2)
mult3 = torch.matmul(m1,m2)    # with broadcast
print(mult3)



tensor([ 9, 12])
tensor([ 9, 12])
tensor([3, 4])
tensor([3, 4])
tensor([2, 2])
tensor([2, 2])
tensor([18, 32])
tensor(50)
tensor([ 9, 12])
tensor([ 9, 12])
tensor([[ 0.4466, -0.0056, -2.8534,  0.6542],
        [-0.9499,  1.4800, -0.7234, -0.8292]])
tensor([[ 0.4466, -0.0056, -2.8534,  0.6542],
        [-0.9499,  1.4800, -0.7234, -0.8292]])
tensor([[ 0.4466, -0.0056, -2.8534,  0.6542],
        [-0.9499,  1.4800, -0.7234, -0.8292]])


## Important Aggregation Functions

In [6]:
x = torch.arange(8.).view(4,2)
print(x)
print(x.sum())
print(x.max())
print(x.min())
print(x.std())
print(x.mean())
print(x.median())


tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.]])
tensor(28.)
tensor(7.)
tensor(0.)
tensor(2.4495)
tensor(3.5000)
tensor(3.)


## Dimension

In [7]:
x = torch.arange(6.).view(3,2)
print(x)
# collapse the specified dimension
print(x.sum(dim=0)) # sum rows. think as x[0] + x[1] + x[2]
print(x.sum(dim=1)) # sum elements of each row. think as x[0].sum() , x[1].sum() , x[2].sum()

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tensor([6., 9.])
tensor([1., 5., 9.])


## Adding or removing dimensions

In [9]:
x = torch.randn(10,28,28)
print(x.shape)
x = x.unsqueeze(dim=1)         # add a new dimension after the first dimension
print(x.shape)
x = x.squeeze()                # remove dimensions of size 1
print(x.shape)

torch.Size([10, 28, 28])
torch.Size([10, 1, 28, 28])
torch.Size([10, 28, 28])
