# Tensors
A tensor is an n-dimensional array.
## Scalar  (0-dimensional tensor)
0 dimesional tensor

In [1]:
import torch

x = torch.tensor(2)                      #  scalar with dtype int64 
y = torch.tensor(2.)                     #  scalar with dtype float32
z = torch.tensor(2, dtype=torch.double)  #  scalar with dtype float64
print("x     :", x)
print("item  :", x.item())                          #  item() returns the scalar value within the tensor
print("dtype :", x.dtype)                           # data type of the tensor values
print("dim   :", x.dim())                           # dimension of the tensor
print("numel :", x.numel())                         # number of elements in the tensor
 

x     : tensor(2)
item  : 2
dtype : torch.int64
dim   : 0
numel : 1


## 1-dimensional tensor

In [2]:
x = torch.tensor([1,2,3,4,5,6])   # Tensor from a list
y = torch.arange(1,7)             # Tensor using arange function
ones = torch.ones(7)
print("x   :", x)
print("y   :", y)
print("ones:", ones)
print("shape x: ", x.shape)
print("size  x: ", x.size())

x   : tensor([1, 2, 3, 4, 5, 6])
y   : tensor([1, 2, 3, 4, 5, 6])
ones: tensor([1., 1., 1., 1., 1., 1., 1.])
shape x:  torch.Size([6])
size  x:  torch.Size([6])


## 2-dimensional tensor, view(), eye(), diag(), zeros()

In [3]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])                       # 2D tensor from list of size 3,2
y = x.view(2,3)                                 # use view() to reshape the tensor
z = x.view(-1,3)                                # -1 states that infer the dimension from the remaining dimensions
t = x.reshape(2,3)                              # same as view but may copy underlying data
t[0,0] = -3
I = torch.eye(4)                                # unit matrix
diags = torch.diag(I)                           # diagonals of a matrix
zeros = torch.zeros(2,3, dtype=torch.int64)     # zero matrix default dtype is float32
print("x:", x)
print("y:", y) 
print("z:", z)
print("t:", t)
print(I)
print(diags)
print(ones)
print(zeros)

x: tensor([[-3,  2],
        [ 3,  4],
        [ 5,  6]])
y: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
z: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
t: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1.])
tensor([[0, 0, 0],
        [0, 0, 0]])


## n-dimensional tensor

In [4]:
x=torch.tensor([[[1,2,3],
                 [3,4,5]],
                [[6,7,9],
                 [9,10,11]]])                  # 3D tensor using list of shape 2,2,3
y = torch.rand(16,1,28,28)                     # uniform dist between 0,1 (16 1-channel(gray scale) 28x28 image)
z = torch.randn(1,1,2,2)                       # from normal distribution mu=0 std=1
ones = torch.ones(2,2,4)
print("x    :",x)
print("size x:", x.size())
print(y)
print(t)

x    : tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[ 6,  7,  9],
         [ 9, 10, 11]]])
size x: torch.Size([2, 2, 3])
tensor([[[[9.7325e-01, 7.5799e-01, 6.7442e-01,  ..., 2.0121e-01,
           6.0320e-01, 8.2125e-01],
          [9.2503e-01, 7.6497e-01, 3.9771e-01,  ..., 8.9065e-01,
           1.9855e-01, 8.6577e-01],
          [3.8976e-01, 7.0542e-01, 5.6404e-01,  ..., 1.5996e-01,
           8.2361e-01, 9.3912e-02],
          ...,
          [9.9044e-01, 2.7743e-01, 5.8876e-01,  ..., 4.6312e-01,
           7.1358e-01, 3.9422e-01],
          [8.8763e-01, 1.0678e-01, 1.3189e-01,  ..., 6.3913e-01,
           5.7226e-01, 8.4973e-01],
          [2.9281e-01, 5.6102e-01, 2.5835e-01,  ..., 9.3170e-01,
           3.5077e-01, 9.4436e-01]]],


        [[[3.2113e-01, 2.6145e-01, 1.0876e-01,  ..., 8.6748e-01,
           4.8499e-01, 5.7688e-01],
          [4.4541e-01, 3.0839e-01, 2.5301e-01,  ..., 4.1791e-01,
           9.3516e-01, 6.2831e-01],
          [4.2650e-01, 8.5428e-01, 6.442

## Aritmetic Operations

In [5]:
x = torch.tensor([6,8])
y = torch.tensor([3,4])
print(x+y)                     # sum
print(x.add(y))                # sum 2
print(x-y)                     # substract
print(x.sub(y))                # substract 2
print(x/y)                     # divide
print(x.div(y))                # divide 2print(torch.matmul(m2,m3))     # broadcasting
print(x*y)                     # element wise product
print(x@y)                     # dot product if both are 1-d tensor

print(x.add_(y))               # inline addition
print(x)                       # value of x has changed

m1 = torch.randn(2, 3)
m2 = torch.randn(3, 4)
m3 = torch.randn(1,3)
mult = torch.mm(m1,m2)         # no broadcast
print(mult)
mult2 = m1 @ m2                # matrix multiplication
print(mult2)
mult3 = torch.matmul(m1,m2)    # with broadcast
print(mult3)



tensor([ 9, 12])
tensor([ 9, 12])
tensor([3, 4])
tensor([3, 4])
tensor([2, 2])
tensor([2, 2])
tensor([18, 32])
tensor(50)
tensor([ 9, 12])
tensor([ 9, 12])
tensor([[ 0.1270,  1.2136,  2.4008,  0.3209],
        [-0.4989,  2.7146,  3.9685,  1.9434]])
tensor([[ 0.1270,  1.2136,  2.4008,  0.3209],
        [-0.4989,  2.7146,  3.9685,  1.9434]])
tensor([[ 0.1270,  1.2136,  2.4008,  0.3209],
        [-0.4989,  2.7146,  3.9685,  1.9434]])


## Important Aggregation Functions

In [6]:
x = torch.arange(8.).view(4,2)
print(x)
print(x.sum())
print(x.max())
print(x.min())
print(x.std())
print(x.mean())
print(x.median())


tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.]])
tensor(28.)
tensor(7.)
tensor(0.)
tensor(2.4495)
tensor(3.5000)
tensor(3.)


## Dimension

In [7]:
x = torch.arange(6.).view(3,2)
print(x)
# collapse the specified dimension
print(x.sum(dim=0)) # sum rows. think as x[0] + x[1] + x[2]
print(x.sum(dim=1)) # sum elements of each row. think as x[0].sum() , x[1].sum() , x[2].sum()

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tensor([6., 9.])
tensor([1., 5., 9.])


## Adding or removing dimensions

In [8]:
x = torch.randn(10,28,28)
print(x.shape)
x = x.unsqueeze(dim=1)         # add a new dimension after the first dimension
print(x.shape)
x = x.squeeze()                # remove dimensions of size 1
print(x.shape)

torch.Size([10, 28, 28])
torch.Size([10, 1, 28, 28])
torch.Size([10, 28, 28])
