# Tensors
A tensor is an n-dimensional array.
## Scalar  (0-dimensional tensor)
0 dimesional tensor

In [27]:
import torch

x = torch.tensor(2)                      #  scalar with dtype int64 
y = torch.tensor(2.)                     #  scalar with dtype float32
z = torch.tensor(2, dtype=torch.double)  #  scalar with dtype float64
print("x     :", x)
print("item  :", x.item())                          #  item() returns the scalar value within the tensor
print("dtype :", x.dtype)                           # data type of the tensor values
print("dim   :", x.dim())                           # dimension of the tensor
print("numel :", x.numel())                         # number of elements in the tensor
 

x     : tensor(2)
item  : 2
dtype : torch.int64
dim   : 0
numel : 1


## 1-dimensional tensor

In [28]:
x = torch.tensor([1,2,3,4,5,6])   # Tensor from a list
y = torch.arange(1,7)             # Tensor using arange function
ones = torch.ones(7)
print("x   :", x)
print("y   :", y)
print("ones:", ones)
print("shape x: ", x.shape)
print("size  x: ", x.size())

x   : tensor([1, 2, 3, 4, 5, 6])
y   : tensor([1, 2, 3, 4, 5, 6])
ones: tensor([1., 1., 1., 1., 1., 1., 1.])
shape x:  torch.Size([6])
size  x:  torch.Size([6])


## 2-dimensional tensor, view(), eye(), diag(), zeros()

In [29]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])                       # 2D tensor from list of size 3,2
y = x.view(2,3)                                 # use view() to reshape the tensor
z = x.view(-1,3)                                # -1 states that infer the dimension from the remaining dimensions
p = x.view(-1)                                  # flatten the 2D tensor to 1D
t = x.reshape(2,3)                              # same as view but may copy underlying data
t[0,0] = -3
I = torch.eye(4)                                # unit matrix
diags = torch.diag(I)                           # diagonals of a matrix
zeros = torch.zeros(2,3, dtype=torch.int64)     # zero matrix default dtype is float32
print("x:", x)
print("y:", y) 
print("z:", z)
print("p", p)
print("t:", t)
print(I)
print(diags)
print(zeros)

x: tensor([[-3,  2],
        [ 3,  4],
        [ 5,  6]])
y: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
z: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
p tensor([-3,  2,  3,  4,  5,  6])
t: tensor([[-3,  2,  3],
        [ 4,  5,  6]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([1., 1., 1., 1.])
tensor([[0, 0, 0],
        [0, 0, 0]])


## n-dimensional tensor

In [30]:
x=torch.tensor([[[1,2,3],
                 [4,5,6]],
                [[7,8,9],
                 [10,11,12]]])                  # 3D tensor using list of shape 2,2,3
y = torch.rand(16,1,28,28)                     # uniform dist between 0,1 (16 1-channel(gray scale) 28x28 image)
z = torch.randn(1,1,2,2)                       # from normal distribution mu=0 std=1
ones = torch.ones(2,2,4)
print("x    :",x)
print("size x:", x.size())
print(z)

x    : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
size x: torch.Size([2, 2, 3])
tensor([[[[ 0.3134, -0.8573],
          [-0.5619, -0.6856]]]])


## Aritmetic Operations

In [31]:
x = torch.tensor([6,8])
y = torch.tensor([3,4])
print(x+y)                     # sum
print(x.add(y))                # sum 2
print(x-y)                     # substract
print(x.sub(y))                # substract 2
print(x/y)                     # divide
print(x.div(y))                # divide 2
print(x*y)                     # element wise product (Hadamard product)
print(x@y)                     # dot product if both are 1-d tensor matrix product otherwise
# matmul, mm

print(x.add_(y))               # inline addition
print(x)                       # value of x has changed


tensor([ 9, 12])
tensor([ 9, 12])
tensor([3, 4])
tensor([3, 4])
tensor([2., 2.])
tensor([2., 2.])
tensor([18, 32])
tensor(50)
tensor([ 9, 12])
tensor([ 9, 12])


## Important Aggregation Functions

In [32]:
x = torch.arange(8.).view(4,2)
print(x)
print(x.sum())
print(x.max())
print(x.min())
print(x.std())
print(x.mean())
print(x.median())


tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.]])
tensor(28.)
tensor(7.)
tensor(0.)
tensor(2.4495)
tensor(3.5000)
tensor(3.)


## Dimension

In [33]:
x = torch.arange(6.).view(3,2)
print(x)
# collapse the specified dimension
print(x.sum(dim=0)) # sum rows. think as x[0] + x[1] + x[2]
print(x.sum(dim=1)) # sum elements of each row. think as x[0].sum() , x[1].sum() , x[2].sum()

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tensor([6., 9.])
tensor([1., 5., 9.])


## Adding or removing dimensions

In [34]:
x = torch.randn(10,28,28)
print(x.shape)
x = x.unsqueeze(dim=1)         # add a new dimension after the first dimension B C H W
print(x.shape)
x = x.squeeze()                # remove dimensions of size 1
print(x.shape)

torch.Size([10, 28, 28])
torch.Size([10, 1, 28, 28])
torch.Size([10, 28, 28])


## Autograd

<img src="images/gradients.jpg">

In [35]:
w1 = torch.tensor([0.2], requires_grad=True)
x1  = torch.tensor([2.0], requires_grad=False)
w0 = torch.tensor([0.1], requires_grad=True)
y = x1*w1 + w0
r = torch.tensor([2])
err = 0.5*(r-y).pow(2)
err.backward()

print(w0.grad)
print(w1.grad)
print(x1.grad)


tensor([-1.5000])
tensor([-3.])
None
